### ISSUE TITLE
Roll and pitch - are mixed up in places.

### ISSUE THREAD

**Issue by b582q9** [arduino/nicla-sense-me-fw#101]
### Description of defect

Roll change should be around X axe and pitch change around Y axe but roll and pitch from SensorOrientation returns this parameters as mixed up

#### Target(s) affected by this defect ?
Arduino Nicla Sense ME

#### What version of Mbed-os are you using (tag or sha) ?
Arduino Mbed OS Nicla Boards 4.0.2

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)
Arduino_BHY2 1.0.6
Arduino IDE 2.1.0

#### How is this defect reproduced ?

```
#include "Arduino.h"
#include "Arduino_BHY2.h"

SensorOrientation orientation(SENSOR_ID_ORI);

void setup()
{
  Serial.begin(115200);
  while(!Serial);
  BHY2.begin();
  orientation.begin();
}

void loop()
{
  BHY2.update(1);   
  Serial.print("Heading = ");
  Serial.println(orientation.heading());
  Serial.print("Pitch = ");
  Serial.println(orientation.pitch());
  Serial.print("Roll = ");
  Serial.println(orientation.roll());
}
```
Move Nicla around **X** axe and you will notice **pitch** change, move around **Y** axe - **roll** will change. It is not right, **should be vice versa.**
![Roll-Pitch-Yaw](https://github.com/arduino/nicla-sense-me-fw/assets/49403742/635dcbb0-4c5a-45af-aa0e-60c206725f00)

![ABX00050_03 front_58d59e81-2475-47a7-8d75-c5136e33d37d_1000x750](https://github.com/arduino/nicla-sense-me-fw/assets/49403742/b8ca7621-689a-410a-96cd-f07c1c15f171)

**Comment by b582q9** [comment]
@bstbud 
It is very strange because there is no pitch, roll or yaw definitions in Android word. It is belong to aviation or robots development.
So, you should change definitions in library (rename pith and roll) or change the behaviour please.

**Comment by bstbud** [comment]
Hi

on page:https://developer.android.com/guide/topics/sensors/sensors_position, it says: 
<html>
<body>


SensorEvent.values[0] | Azimuth (angle around the z-axis). | Degrees
-- | -- | --
SensorEvent.values[1] | Pitch (angle around the x-axis).
SensorEvent.values[2] | Roll (angle around the y-axis).


</body>
</html>

**Comment by b582q9** [comment]
@bstbud 
Ok, you made it like it shouldn't :).
But, maybe you could make a lib version with a definitions like in aviation? It will be very useful for those who want to use nicla for avionics.

**Comment by per1234** [comment]
I see the information is already specified in the documentation:

https://docs.arduino.cc/tutorials/nicla-sense-me/getting-started#sensororientation

so I'll close this issue.

>maybe you could make a lib version with a definitions like in aviation?

You are welcome to create such a library @b582q9
