### ISSUE TITLE
Micropython support for Nicla Sense

### ISSUE THREAD

**Issue by dspreitz** [arduino/nicla-sense-me-fw#123]
Do you have any plans to also offer Micropython support for Nical Sense? Nicla vision is already supported my micropython.

**Comment by facchinm** [comment]
Nicla Sense and Nicla Vision are based on very different MCUs (nRF5283 vs STM32H747). The Sense doesn't ship with enough RAM to make it a suitable target for Micropython (it would run, but with severe limitations).

**Comment by dspreitz** [comment]
Martino,Thanks for the clarification and Background Info.Appreciated.Am 09.01.2024 11:52 schrieb Martino Facchin ***@***.***>:
Nicla Sense and Nicla Vision are based on very different MCUs (nRF5283 vs STM32H747). The Sense doesn't ship with enough RAM to make it a suitable target for Micropython (it would run, but with severe limitations).
